//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AuditID { get; set; }
        public int UserID { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
